<a href="https://colab.research.google.com/github/neilkazimierzsheridan/data_science_course/blob/main/ds_Numpy3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Numpy Operations
import numpy as np

In [3]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
#add 5 to each element
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
arr - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [6]:
#still elementwise when with another array
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [8]:
#dividing by zero will still give a result, 0/0 replaced with NAN (not a number)
#DANGER HERE BECAUSE NO ERROR JUST A WARNING!
arr / arr

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [9]:
1/ arr #gives is a result with an infinity placeholder

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [10]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [11]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [12]:
np.log(arr) #warning for zero

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [13]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr.sum()

45

In [15]:
arr.max()

9

In [16]:
arr.var() #variance

8.25

In [17]:
arr.std() #SD

2.8722813232690143

In [19]:
#Look at a 2 dimensional array
array2d = np.arange(0,25).reshape(5,5)
array2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [20]:
array2d.sum()
#But what if just want sum of some rows or columns?

300

In [21]:
array2d.sum(axis=0) 
#this takes axis argument. axis zero is across the rows giving the sum of columns!
# i.e. 0+5+10+15+20, 1+6+11+16+21, etc.

array([50, 55, 60, 65, 70])

In [22]:
array2d.sum(axis=1)
#operation across the columns - yes this gives the sum of rows haha
# i.e. 0+1+2+3+4, etc.

array([ 10,  35,  60,  85, 110])

In [24]:
account_transactions = np.array([100,-200,300,-400,100,100,-230,450,500,2000])
account_transactions #this is the quiz question

array([ 100, -200,  300, -400,  100,  100, -230,  450,  500, 2000])

In [25]:
account_transactions.sum()

2720

In [29]:
nums = [100,200,-100] #check it would be correct
test_array = np.array(nums)
test_array
test_array.sum()

200