<a href="https://colab.research.google.com/github/neilkazimierzsheridan/data_science_course/blob/main/ds_Numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#indexing and selection
#1. Grabbing a single element
import numpy as np


In [2]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8] #get 8

8

In [5]:
arr[:5] #beginning to 5

array([0, 1, 2, 3, 4])

In [6]:
arr[5:] #5 to end

array([ 5,  6,  7,  8,  9, 10])

In [7]:
#broadcasting
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
#grab all numbers from 0-5 and set to 100, 100 broadcast accross these values
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [10]:
arr = np.arange(0,11)

In [12]:
slice_of_arr = arr[0:5] #slice 0-5
slice_of_arr

array([0, 1, 2, 3, 4])

In [13]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
slice_of_arr[:] = 99 #so broadcast 99 across all elements in the array
slice_of_arr

array([99, 99, 99, 99, 99])

In [17]:
arr
#Hold up the broadcasting operation has affected the original array!
# Because of slice_of_arr = arr[0:5]

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [19]:
#so don't forget to do a copy if not wanting to affect original
arr_copy = arr.copy()
arr_copy[:] = 100 
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [20]:
#See the original is fine now!
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [22]:
#2. Indexing on 2d arrays
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d #3*3

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [23]:
arr_2d.shape Index 0 = rows Index 1 = columns

(3, 3)

In [24]:
arr_2d[0] #first row

array([ 5, 10, 15])

In [25]:
arr_2d[1] #second row

array([20, 25, 30])

In [26]:
arr_2d[2] #third row

array([35, 40, 45])

In [27]:
#get me one element from 2 from the 2nd row (25)
arr_2d[1][1]

25

In [28]:
#or like this
arr_2d[1,1]

25

In [29]:
#get me first element on first row (5)
arr_2d[0,0]

5

In [30]:
#now for slicing like this
arr_2d[:2] #so I want the first two rows 0,1

array([[ 5, 10, 15],
       [20, 25, 30]])

In [31]:
#Now I want to grab the last two elements in each of the first two rows
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [32]:
#Or I might just want the first element in the first two rows
arr_2d[:2,0:1]

array([[ 5],
       [20]])

In [33]:
#3 Conditional Selection
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
#broadcast a condition (comparison) off this e.g. where is my array > 4??
arr > 4 #BOOM!

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [35]:
bool_arr = arr >4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [36]:
#use this bool_arr to filter the original array
filtered_arr = arr[bool_arr]
filtered_arr

array([ 5,  6,  7,  8,  9, 10])

In [38]:
#or just this kinda thing
filtered_arr2 = arr[arr>4]
filtered_arr2

array([ 5,  6,  7,  8,  9, 10])

In [39]:
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])

In [40]:
dice_rolls #this was the quiz question

array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6,
       3, 6, 2, 3, 5, 6, 5])

In [41]:
#filter it as per above to find rolls greater than 2
over2_arr = dice_rolls[dice_rolls>2]
over2_arr

array([3, 5, 5, 5, 4, 4, 5, 3, 4, 5, 4, 6, 6, 3, 6, 3, 5, 6, 5])

In [42]:
len(over2_arr)

19