<a href="https://colab.research.google.com/github/neilkazimierzsheridan/data_science_course/blob/main/ds_Numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [6]:
#make a numpy array from a python list
my_list = [1,2,3]
type(my_list)
np.array(my_list)

myarr = np.array(my_list)
type(myarr)

# matrix 2 dimensions 

my_matrix = [[1,2,3], [4,5,6], [7,8,9]]
my_matrix

np.array(my_matrix) #BAM!

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,10) #like python range making a numpy array

#let me put in a step size of 2
np.arange(0,101,2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [14]:
#all zeros, pass in shape
np.zeros((2,5)) #rows then columns

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones((4,3)) #it's ONES!

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.linspace(0,10, 11) 
#even (linearly) spaced over specified interval: start, stop, num=? how many inbetween?

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [21]:
len(np.linspace(0,5,21))

21

In [22]:
np.eye(5) ones on the main diagonal (identity matrix)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
#random distributions to create
np.random.rand(2,3) # rows * columns // don't pass tuples 

array([[0.892725  , 0.09606636, 0.87471796],
       [0.96995393, 0.76078912, 0.57053785]])

In [30]:
#standard normal distribution
np.random.randn(2,3)

array([[-1.44584996, -0.81457805,  0.46924389],
       [-0.8971397 ,  0.18890351,  0.32548343]])

In [33]:
np.random.randint(0, 101, 5) #range and how many 0-101 num=5
#get the random integers!

array([52, 28, 83, 29, 79])

In [34]:
#setting the seed 
#guess why everyone uses 42 LOL!

np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [36]:
#attributes and method calls
arr = np.arange(0,25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [37]:
arr.reshape(5,5) #reshape but they have to fit into the new shape!

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [39]:
ranarr = np.random.randint(0,101,10)
ranarr

array([ 1, 87, 29, 37,  1, 63, 59, 20, 32, 75])

In [40]:
ranarr.max()

87

In [41]:
ranarr.min()

1

In [42]:
ranarr.argmax() #give the index location for max

1

In [43]:
ranarr.argmin() #idx loc for min

0

In [44]:
ranarr.dtype #datatype

dtype('int64')

In [45]:
arr.shape #SHAPES

(25,)

In [46]:
ranarr.shape

(10,)

In [47]:
arr = arr.reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [48]:
arr.shape

(5, 5)

In [49]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [50]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [51]:
np.linspace(0,10,101) #this was the quiz question

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])